name: Check elixir-phoenix

on:
  push:
    paths:
      # Set this to the directory of the template
      - elixir-phoenix/**
      - .github/workflows/check-elixir-phoenix.yml
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v17

      - uses: actions/checkout@v3
        with:
          path: ./tmp
      - run: nix flake init -t ./tmp#elixir-phoenix
      - name: Prepare the project
        run: |
          rm -rf ./tmp
          git init
          git add .

      - name: Check executables
        run: |
          nix develop --command mix help
          nix develop --command elixir --version
