name: Check minimal

on:
  push:
    # Set this to the directory of the template
    paths:
    - minimal/**

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v17
    # Run any task to check your flake
    - working-directory: minimal
      run: nix build '.#hello'
