name: Check elixir

on:
  push:
    paths:
      # Set this to the directory of the template
      - elixir/**
      - .github/workflows/check-elixir.yml
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v18

      - uses: actions/checkout@v3
        with:
          path: ./tmp
      - run: nix flake init -t ./tmp#elixir
      - name: Prepare the project
        run: |
          rm -rf ./tmp
          git init
          git add .

      - name: Check executables
        run: |
          nix develop --command mix help
          nix develop --command elixirc --version
