name: Check minimal

on:
  push:
    paths:
    # Set this to the directory of the template
    - minimal/**
    - .github/workflows/check-minimal.yml
  workflow_dispatch:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v3
      with:
        path: ./tmp
        ref: ${{ inputs.ref }}
    - run: nix flake new -t ./tmp#minimal ./work
    - name: Prepare the project
      working-directory: work
      run: |
        git init
        git add .

    # Run any task to check your flake
    - run: nix build '.#hello'
      working-directory: work
