name: Check node-typescript

on:
  push:
    paths:
    - node-typescript/**
    - .github/workflows/check-node-typescript.yml
  workflow_dispatch:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: cachix/install-nix-action@v19
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v3
      with:
        path: ./tmp
        ref: ${{ inputs.ref }}
    - run: nix flake new -t ./tmp#node-typescript ./work
    - name: Prepare the project
      working-directory: work
      run: |
        git init
        git add .

    - run: nix develop -c pnpm --version
      working-directory: work
    - run: nix develop -c tsc --version
      working-directory: work
    - run: nix develop -c typescript-language-server --version
      working-directory: work
