name: Check elixir-phoenix

on:
  push:
    paths:
      # Set this to the directory of the template
      - elixir-phoenix/**
      - .github/workflows/check-elixir-phoenix.yml
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v18

      - uses: actions/checkout@v3
        with:
          path: ./tmp
      - run: nix flake new -t ./tmp#elixir-phoenix ./work
      - name: Prepare the project
        working-directory: work
        run: |
          git init
          git add .

      - name: Check executables
        working-directory: work
        run: |
          nix develop --command mix help
          nix develop --command elixirc --version
