name: Check node-typescript

on:
  push:
    paths:
    - node-typescript/**
    - .github/workflows/check-node-typescript.yml
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: cachix/install-nix-action@v18

    - uses: actions/checkout@v3
      with:
        path: ./tmp
    - run: nix flake init -t ./tmp#node-typescript
    - name: Prepare the project
      run: |
        rm -rf ./tmp
        git init
        git add .

    - run: nix develop -c pnpm --version
    - run: nix develop -c tsc --version
    - run: nix develop -c typescript-language-server --version
