name: Check elixir-phoenix

on:
  push:
    paths:
      # Set this to the directory of the template
      - elixir-phoenix/**
      - .github/workflows/check-elixir-phoenix.yml
  workflow_dispatch:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
        with:
          path: ./tmp
          ref: ${{ inputs.ref }}

      - run: nix flake new -t ./tmp#elixir-phoenix ./work
      - name: Prepare the project
        working-directory: work
        run: |
          git init
          git add .

      - name: Check executables
        working-directory: work
        run: |
          nix develop --command mix help
          nix develop --command elixirc --version
