name: Update

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: cachix/install-nix-action@v17

    - name: Update flake inputs
      run: nix flake lock --update-input nixpkgs

    - name: Update Erlang and Elixir
      run: nix run .#update-beam
      continue-on-error: true
      id: updated

    - name: Roll back if there is no modification
      run: git reset --hard ${{ github.sha }}
      if: ${{ steps.updated.outcome == 'failure' }}

    - uses: peter-evans/create-pull-request@v4
      id: pr
      with:
        commit-message: 'Update'
        base: master
        title: 'chore: Update language runtime'
        branch: create-pull-request/update
        labels: automation,update
